### ISSUE TITLE
[Error] authentication required

### ISSUE THREAD

**Issue by cerberus10** [ONLYOFFICE/docker-onlyoffice-nextcloud#12]
Fresh Ubuntu server 18.10 vm with latest docker and docker compose installed throws error "authentication required (...) failed" and the postinstall script faills.

Maybe there is some an error on the docker-hub permissions on some of the other repos this repository  uses??.
 
I thought none of the onlyoffice or nexcloud repositories requiered  login or permissions. 

Any ideas?

**Comment by ShockwaveNN** [comment]
@cerberus10 Hi, just checked by `docker-compose up` and everything seems fine. Maybe your `docker` or `docker compose` are old?

**Comment by cerberus10** [comment]
Dont think so 
![image](https://user-images.githubusercontent.com/8902482/52300802-9635f680-2967-11e9-973d-08af96869bc3.png)

**Comment by ShockwaveNN** [comment]
@cerberus10 so, to be sure - you get this error on `docker pull onlyoffice/documentserver:latest`?

**Comment by cerberus10** [comment]
using the docker-composer script. Using  "docker pull .."" I have the same result ,
![image](https://user-images.githubusercontent.com/8902482/52347125-f8423a80-29ff-11e9-9b75-ecee72d8026d.png)

**Comment by ShockwaveNN** [comment]
@cerberus10 I don't think that the reason of this error somehow related to us.
I googled it and found some possible solutions at https://github.com/jupyter/docker-stacks/issues/484
The reason maybe incorrect clock time. or proxy.

**Comment by cerberus10** [comment]
Sorry you were right the server was no reaching the ntp server and was  1 minute behind .
