### ISSUE TITLE
reverse proxy have a little trouble with scheme

### ISSUE THREAD

**Issue by carlsue** [ONLYOFFICE/docker-onlyoffice-nextcloud#14]
my nginx reverse proxy config well(for http to https),and everything is ok, have a little trouble with scheme some place:
![TIM截图20190312141439](https://user-images.githubusercontent.com/17507066/54178974-5fa54b80-44d2-11e9-861e-028e0d167ca9.jpg)
![TIM截图20190312141511](https://user-images.githubusercontent.com/17507066/54178910-37b5e800-44d2-11e9-8ae7-5f7698f06589.jpg)
![TIM截图20190312142108](https://user-images.githubusercontent.com/17507066/54178913-384e7e80-44d2-11e9-90b7-3edc9d5a4723.jpg)

**Comment by CarlOnlyoffice** [comment]
Hi @carlsue 
Please address this question to Nextcloud team as it has nothing to do with ONLYOFFICE app.

**Comment by carlsue** [comment]
> Hi @carlsue
> Please address this question to Nextcloud team as it has nothing to do with ONLYOFFICE app.

ok,i will.  but i have some error with onlyoffice.
[nextcloud.log](https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud/files/2959362/nextcloud.log)

**Comment by CarlOnlyoffice** [comment]
@carlsue This error does not affect the functioning of the document editing and will be fixed in the next version of ONLYOFFICE connector app.

**Comment by carlsue** [comment]
> @carlsue This error does not affect the functioning of the document editing and will be fixed in the next version of ONLYOFFICE connector app.

ok

**Comment by carlsue** [comment]
nextcloud problem fixed ,thanks!
add override protocol https
