### ISSUE TITLE
FastCGI timout

### ISSUE THREAD

**Issue by eeshugerman** [ONLYOFFICE/docker-onlyoffice-nextcloud#19]
This has worked for me a couple times, but ~80% of the time after doing the initial `docker-compose up`, when I try to open the app in the browser, it just spins for a while and then:
![image](https://user-images.githubusercontent.com/25518211/64902534-ed224d80-d665-11e9-940b-525ee7e92f5e.png)
and the logs show:
```
nginx-server                  | 2019/09/14 02:20:43 [error] 6#6: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.0.2.2, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.4:9000", host: "localhost:8888"
```

I haven't been able to narrow down any factor that determines whether or not it will work. I have tried waiting a while (15+ minutes) before loading the app but this doesn't seem to make a difference.

I am running this on Ubuntu 18.04 in a VM. Any ideas? Let me know if there is any more information I can provide.

Thanks!

**Comment by eeshugerman** [comment]
Never mind, I realized that the problem started when I tried adding postgres :man_facepalming:. I will update here if I find a solution.

**Comment by eeshugerman** [comment]
The issue was I needed to add the postgres service to the `onlyoffice` network (or remove said network entirely).

**Comment by zeddit** [comment]
The issue happened again for nextcloud:fpm 21.0.1.
504 gateway timed out when trying to initialize nextcloud.
