### ISSUE TITLE
Nextcloud first run ask for infos...

### ISSUE THREAD

**Issue by gilluc** [ONLYOFFICE/docker-onlyoffice-nextcloud#27]
At Installation Step 3 you say:
Enter all the necessary data to complete the wizard.

where can i find DATABASE NAME, USER , PASSword .... ???

thanks in advance
gilles

**Comment by gilluc** [comment]
trying to fill data and everything ends with

> Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory

**Comment by HelenBelova17** [comment]
Hello, @**gilluc**, just fill Username and Password fields only.

**Comment by gilluc** [comment]
Doesn't work

⁣.................
Gilles Lucato
gilles@lucato.com
................ 

Télécharger BlueMail pour Android ​

Le 20 janv. 2020 à 08:53, à 08:53, Elena Belova <notifications@github.com> a écrit:

**Comment by HelenBelova17** [comment]
By default, this container uses SQLite for data storage if you want to use another go to https://github.com/nextcloud/docker for settings.

**Comment by gilluc** [comment]
yes helen, this container cannot work with anything else than sqlite!!
