### ISSUE TITLE
FATAL:  could not write lock file "postmaster.pid": No space left on device

### ISSUE THREAD

**Issue by faziz** [ONLYOFFICE/docker-onlyoffice-nextcloud#28]
I am getting the following error,

root@indus:~/sources/docker-onlyoffice-nextcloud# docker-compose up
Starting onlyoffice-document-server ... done
Starting nginx-server               ... done
Starting app-server                 ... done
Attaching to onlyoffice-document-server, nginx-server, app-server
app-server                    | [13-Feb-2020 10:28:34] NOTICE: fpm is running, pid 1
app-server                    | [13-Feb-2020 10:28:34] NOTICE: ready to handle connections
onlyoffice-document-server    |  * Starting PostgreSQL 9.5 database server       * The PostgreSQL server failed to start. Please check the log output:
onlyoffice-document-server    | 2020-02-13 10:28:34 UTC [126-1] FATAL:  could not write lock file "postmaster.pid": No space left on device
onlyoffice-document-server    |                                          [fail]
onlyoffice-document-server    |  * Starting RabbitMQ Messaging Server rab[ OK ] erver       
onlyoffice-document-server    | Starting redis-server: redis-server.
onlyoffice-document-server    | Waiting for connection to the localhost host on port 5432

I have disk space available on my computer.

**Comment by HelenBelova17** [comment]
Hi @**faziz**
It seems you do not have free disk space. Clean up disk space. This is not a problem with this installation.

**Comment by faziz** [comment]
Yeah I got it sorted out, thanks.
