### ISSUE TITLE
Host violates local access rules

### ISSUE THREAD

**Issue by Ivan-Igorevich** [ONLYOFFICE/docker-onlyoffice-nextcloud#34]
Hello! I am using this docker-compose build, thanks a lot for it. But faced a little problem: as I upload a `docx` file and try to convert it to `OO` format by right-clicking and selecting the corresponding menu entry - I got the notification in top-right corner of the app `Host violates local access rulesHost violates local access rules`. Where are those rules set? Can u, please, provide me some help with this?

**Comment by HelenBelova17** [comment]
Hello @**Ivan-Igorevich**,
add this line to config.php:
`'allow_local_remote_servers' => true,`

**Comment by Ivan-Igorevich** [comment]
thank you, do i need to recreate or restart containers?
