### ISSUE TITLE
Update NextCloud

### ISSUE THREAD

**Issue by LinuxOperator** [ONLYOFFICE/docker-onlyoffice-nextcloud#46]
Hello,
I am trying to update my Nexcloud to the latest version and don't see a way to do it.
The "Open updater" takes me to a page that doesn't exist (`https://<my server ip>/updater`) and I don't see any documentation on how to perform updates.

This is the screen I am looking at:

   ![image](https://user-images.githubusercontent.com/68796633/104514643-9614eb80-55bf-11eb-88d4-fa226c6fb01e.png)

**Can anyone tell me how to install this?**
Also I updated the OnlyOffice App within the web interface, would this need any additional updates in the future?

Thank you!

**Comment by SergeyKorneyev** [comment]
Hello,
Please contact the Nextcloud team to get help updating the **nextcloud:fpm** container. As for the OnlyOffice connector app, we do release new versions for it, so you might want to update it in the future as well.

**Comment by LinuxOperator** [comment]
I found out that the docker container I am using is still the latest version (update not available in docker format yet).

Found a guide that should work for others looking for the answer to this question:
```
docker pull nextcloud
docker ps
```
_Look for your nextcloud:fpm container ID_
```
docker stop <your_nextcloud_container_ID>
docker rm <your_nextcloud_container_ID>
docker-compose up -d
```
