### ISSUE TITLE
docker-compose up -d  so slowly

### ISSUE THREAD

**Issue by wqtb** [ONLYOFFICE/docker-onlyoffice-nextcloud#48]
what I can do is just waiting after I run the command 'docker-compose up -d', the download speed get more and more slow tilll nothing speed at all.

**Comment by ShockwaveNN** [comment]
I think it's a network or hub.docker.com issues and has nothing to do with our product itself.

You can download images via calling for example `docker pull nextcloud:fpm` for [this line](https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud/blob/ebcbcb1761c1fe76c8648828f60c680c8b9587e2/docker-compose.yml#L5) in `docker-compose` and same for others

**Comment by wqtb** [comment]
> I think it's your network or hub.docker.com issues and has nothing to do with our product itself.
> 
> You can download images via calling for example `docker pull nextcloud:fpm` for [this line](https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud/blob/ebcbcb1761c1fe76c8648828f60c680c8b9587e2/docker-compose.yml#L5) in `docker-compose` and same for others

yes,I have addressed this issue perfectly. thank you

**Comment by ShockwaveNN** [comment]
In that case I'll close your issue
