### ISSUE TITLE
where to use php occ install app 

### ISSUE THREAD

**Issue by wqtb** [ONLYOFFICE/docker-onlyoffice-nextcloud#52]
I want to install an app with OCC, the official documents said for using  OCC I need into /var/www/nextcloud, however, I install nextcloud with this image. and I can't find /var/www/nextcloud.

**Comment by LinneyS** [comment]
Hi @wqtb 
Please watch this https://github.com/nextcloud/docker#using-the-nextcloud-command-line-interface
