### ISSUE TITLE
First Run issues

### ISSUE THREAD

**Issue by sirsean12** [ONLYOFFICE/docker-onlyoffice-nextcloud#8]
Thanks in advanced.

How do I connect to mysql/Maria on first run?
Is there a default username and password?
do I need to setup the database myself?

It would be nice to actually document this in the README. Clear instructions seem to be an issue with these docker containers. If the info is somewhere else perhaps a simple copy and paste is not asking too much?

Thank you!

**Comment by ibnpetr** [comment]
Hello 
We would recommend to use Nextcloud instructions section where you can find all necessary options for configuring your containers.
For example [here](https://github.com/nextcloud/docker/tree/master/.examples) you can find some examples of the docker-compose files
