### ISSUE TITLE
OnlyOffice functions not working on Raspberry Pi 4 install

### ISSUE THREAD

**Issue by christyler80** [ONLYOFFICE/docker-onlyoffice-nextcloud#85]
Error 1 - from the OnlyOffice container when trying to open a .docx document:

-02T08:54:59.067] [ERROR] [localhost] [conv_3807696080_jpeg] [userId] nodeJS - error downloadFile:url=http://nginx-server/index.php/apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJkb3dubG9hZCIsImZpbGVJZCI6MjksInVzZXJJZCI6ImFkbWluIn0.LXtGVZ98s9h_TcTlUiNIGBoRuxZMpnZy0spfgB3JzS4;attempt=3;code:undefined;connect:undefined Error: Error response: statusCode:400; headers:{"server":"nginx","date":"Fri, 02 Jun 2023 08:54:59 GMT","content-type":"text/html; charset=UTF-8","transfer-encoding":"chunked","connection":"keep-alive","x-powered-by":"PHP/8.2.6","set-cookie":["oc_sessionPassphrase=jlEtzMgLhoRtD93A2omnoqmPytCbUzZm8Oe5WCpq68OF5PvOTIqPrCNplgt1WeWyP9TOkSkdjlNlcPspuRKwfRhQqW26VxPI0cIfbUWrtuFv%2B4IoLIL%2FWRciWxzJ9BGk; path=/; HttpOnly; SameSite=Lax","nc_sameSiteCookielax=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","nc_sameSiteCookiestrict=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict","oc6thb68yly5=66e409451e93fdd9f2e14ffaecbc048b; path=/; HttpOnly; SameSite=Lax"],"content-security-policy":"default-src 'self'; script-src 'self' 'nonce-SXEvM1FZZC9pc01ZTkhsU3RSRjZ6R3gwbmJPUE5BRVJ1L3dSbnFTdENlbz06Q2Q2ZU9NVTk1NnAzQnhVRGpXSkNpaHNDMUp6Yld6SmUvNHA5eWUzYVBLaz0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';","expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

Error 2 - when trying to select 'Connect to ONLYOFFICE Docs Server'

Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 7.3.3.49)

**Comment by christyler80** [comment]
Now working when I re-installed after shutting down my proxy server Traefik. Not sure why that should make any difference, but seems to be Ok.

**Comment by SergeyKorneyev** [comment]
Glad to hear it's resolved! Let us know if you run into any other issues with the setup
