### ISSUE TITLE
nextcloud without fpm

### ISSUE THREAD

**Issue by JAugusto42** [ONLYOFFICE/docker-onlyoffice-nextcloud#9]
Its possible use nextcloud with onlyoffice without fpm?

**Comment by olivy70** [comment]
@JAugusto42 
Hi !

I read that in december 2018 you had the same problem as me with OnlyOffice in Nextcloud.

error ESOCKETTIMEOUT when editing a large file.

DId you solve the problem and how ?

Thanks a lot.
Best regards,
[https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud/issues/31#issue-606131321](url)

**Comment by JAugusto42** [comment]
Hi, it was a long time ago and I don't remember.
